CREATE OR REPLACE TRIGGER TRG_UPDATE_VEC
BEFORE INSERT OR UPDATE ON XPTO_PRODUTOS
FOR EACH ROW
BEGIN
  SELECT VECTOR_EMBEDDING(
           XPTO_STORE.ALL_MINILM_L12_V2
           USING :NEW.NOME || :NEW.DESCRICAO AS DATA
         )
    INTO :NEW.VETOR_DESCRICAO
    FROM dual;
END;
